### ISSUE TITLE
TypeError: fwrite(): supplied resource is not a valid stream resource in /home/user/public_html/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php:178

### ISSUE THREAD

**Issue by eugenefvdm** [Payfast/mod-whmcs#9]
Every since I upgraded to PHP 8.1 on our WHMCS server, the Payfast module is failing with the following error:

```
* Connection #0 to host api.payfast.co.za left intact
  6/34 [▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░]  17% 7 mins/42 mins 54.5 MiB[WHMCS Application] ERROR: TypeError: fwrite(): supplied resource is not a valid stream resource in /home/user/public_html/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php:178 Stack trace: #0 /home/user/public_html/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php(178): fwrite() #1 /home/user/public_html/modules/gateways/payfast.php(350): Payfast\PayfastCommon\PayfastCommon::pflog() #2 [internal function]: Payfast_capture() #3 /home/user/public_html/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func() #4 /home/user/public_html/vendor/whmcs/whmcs-foundation/lib/Module/Gateway.php(0): WHMCS\Module\AbstractModule->call() #5 /home/user/public_html/includes/ccfunctions.php(0): WHMCS\Module\Gateway->call() #6 /home/user/public_html/includes/ccfunctions.php(0): captureCCPayment() #7 /home/user/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Task/ProcessCreditCardPayments.php(0): ccProcessing() #8 [internal function]: WHMCS\Cron\Task\ProcessCreditCardPayments->__invoke() #9 /home/user/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): call_user_func_array() #10 /home/user/public_html/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute() #11 /home/user/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run() #12 /home/user/public_html/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection() #13 /home/user/public_html/vendor/symfony/console/Command/Command.php(298): WHMCS\Cron\Console\Command\AbstractCronCommand->execute() #14 /home/user/public_html/vendor/symfony/console/Application.php(1028): Symfony\Component\Console\Command\Command->run() #15 /home/user/public_html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand() #16 /home/user/public_html/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun() #17 /home/user/whmcs/crons/cron.php(0): Symfony\Component\Console\Application->run() #18 {main} {"exception":"[object] (TypeError(code: 0): fwrite(): supplied resource is not a valid stream resource at /home/user/public_html/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php:178)"} []
TypeError: fwrite(): supplied resource is not a valid stream resource in /home/user/public_html/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php:178
```

Any clues where to start with this error?

**Comment by appinlet** [comment]
Hi @eugenefvdm,

Please note that this issue has been patched in https://github.com/Payfast/mod-whmcs/releases/tag/v2.2.6

**Comment by CubenetWebHosting** [comment]
Hi

I have V2.2.6 and I get this, not sure if it is the same issue or a new issue.

Please have alook


```

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Oops!</title>
    
<style>
        body {
            margin: 30px 40px;
            background-color: #f6f6f6;
        }
        .error-container {
            padding: 50px 40px;
            font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
            font-size: 14px;
        }
        h1 {
            margin: 0;
            font-size: 48px;
            font-weight: 400;
        }
        h2 {
            margin: 0;
            font-size: 26px;
            font-weight: 300;
        }
        a {
            color: #336699;
        }
        p.back-to-home {
            margin-top: 30px;
        }
        p.debug{
            padding: 20px 0;
            font-family: "Courier New", Courier, monospace, serif;
            font-size: 14px;
        }
        .info {
            border: solid 1px #999;
            padding: 5px;
            background-color: #d9edf7;
        }
    </style>

  </head>
  <body>
    <div class="error-container">
<h1>Oops!</h1>
<h2>Something went wrong and we couldn't process your request.</h2>
<p>Please go back to the previous page and try again.</p>
<p class="debug"><br/>TypeError: fwrite(): supplied resource is not a valid stream resource in /home/whmcs/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php:179<br />
Stack trace:<br />
#0 /home/whmcs/modules/gateways/payfast/vendor/payfast/payfast-common/src/PayfastCommon.php(179): fwrite(Resource id #965, '2023-10-31 08:0...')<br />
#1 /home/whmcs/modules/gateways/payfast.php(350): Payfast\PayfastCommon\PayfastCommon::pflog('Payfast capture...')<br />
#2 [internal function]: Payfast_capture(Array)<br />
#3 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/AbstractModule.php(0): call_user_func('payfast_capture', Array)<br />
#4 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Module/Gateway.php(0): WHMCS\Module\AbstractModule->call('capture', Array)<br />
#5 /home/whmcs/includes/ccfunctions.php(0): WHMCS\Module\Gateway->call('capture', Array)<br />
#6 /home/whmcs/includes/ccfunctions.php(0): captureCCPayment(59021)<br />
#7 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Cron/Task/ProcessCreditCardPayments.php(0): ccProcessing(Object(WHMCS\Cron\Task\ProcessCreditCardPayments))<br />
#8 [internal function]: WHMCS\Cron\Task\ProcessCreditCardPayments->__invoke()<br />
#9 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): call_user_func_array(Object(WHMCS\Cron\Task\ProcessCreditCardPayments), Array)<br />
#10 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Scheduling/Task/AbstractTask.php(0): WHMCS\Scheduling\Task\AbstractTask->execute()<br />
#11 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Scheduling\Task\AbstractTask->run()<br />
#12 /home/whmcs/vendor/whmcs/whmcs-foundation/lib/Cron/Console/Command/AbstractCronCommand.php(0): WHMCS\Cron\Console\Command\AbstractCronCommand->executeCollection(Object(WHMCS\Scheduling\Task\Collection))<br />
#13 /home/whmcs/vendor/symfony/console/Command/Command.php(298): WHMCS\Cron\Console\Command\AbstractCronCommand->execute(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))<br />
#14 /home/whmcs/vendor/symfony/console/Application.php(1028): Symfony\Component\Console\Command\Command->run(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))<br />
#15 /home/whmcs/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(WHMCS\Cron\Console\Command\AllCommand), Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))<br />
#16 /home/whmcs/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))<br />
#17 /home/whmcs/crons/cron.php(0): Symfony\Component\Console\Application->run(Object(WHMCS\Cron\Console\Input\HttpInput), Object(Symfony\Component\Console\Output\BufferedOutput))<br />
#18 {main}</p></div>
  </body>
</html>
```
